pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building the project...'
                sh 'mvn clean package'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("demo-spring-boot:latest", ".")
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                        docker.image("demo-spring-boot:latest").push()
                    }
                }
            }
        }
        stage('Cleanup') {
            steps {
                sh 'mvn clean'
            }
        }
    }
}
